FROM node:20-alpine
WORKDIR /app

# Python sidecar: the Excel workbook is generated by the parity-locked assets/build_excel.py
# (openpyxl is pure-Python, no build tools needed). The interactive HTML tool is pure Node.
RUN apk add --no-cache python3 py3-pip \
  && pip3 install --no-cache-dir --break-system-packages openpyxl

COPY package.json package-lock.json* ./
RUN npm install --omit=dev

COPY src ./src/
COPY assets ./assets/

EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -q --spider http://localhost:3000/healthz || exit 1
CMD ["node", "src/server.js"]
